# Generated by Django 5.2.7 on 2025-10-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
