# Generated by Django 5.2.7 on 2025-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
