# Generated by Django 5.2.7 on 2025-10-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0003_rename_status_order_order_status_and_more'),
        ('products', '0007_product_avg_rating'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
