# Generated by Django 5.2.7 on 2025-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
