# Generated by Django 5.2.7 on 2026-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Need Help with a Return?', max_length=255)),
                ('heading1', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
                ('heading2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return Help',
                'verbose_name_plural': 'Return Help',
            },
        ),
    ]
