# Generated by Django 5.2.7 on 2026-02-17 17:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoosesection',
            name='card_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychoosesection',
            name='card_heading',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='whychoosesection',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='whychoosesection',
            name='heading1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='whychoosesection',
            name='heading2',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='WhyChooseCard',
        ),
    ]
