# Generated by Django 5.2.7 on 2026-02-17 21:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_der'),
    ]

    operations = [
        migrations.AlterField(
            model_name='der',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
