# Generated by Django 5.2.7 on 2026-02-17 21:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_der_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, null=True)),
                ('icon1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon1')),
                ('heading2', models.CharField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('icon2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon2')),
                ('heading3', models.CharField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('icon3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon3')),
                ('heading4', models.CharField(blank=True, max_length=255, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('icon4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon4')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
