# Generated by Django 5.2.7 on 2026-02-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Section'},
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
