# Generated by Django 5.2.7 on 2026-02-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contactinfo_alter_section_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychoosesection',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='whychoosesection',
            name='heading2',
        ),
    ]
