# Generated by Django 5.2.7 on 2026-03-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_whychoosesection_heading1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=255)),
                ('subheading1', models.CharField(max_length=255)),
                ('heading2', models.CharField(max_length=255)),
                ('subheading2', models.CharField(max_length=255)),
                ('heading3', models.CharField(max_length=255)),
                ('subheading3', models.CharField(max_length=255)),
                ('heading4', models.CharField(max_length=255)),
                ('subheading4', models.CharField(max_length=255)),
                ('heading5', models.CharField(max_length=255)),
                ('subheading5', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heading Section',
                'verbose_name_plural': 'Heading Sections',
            },
        ),
    ]
