# Generated by Django 5.2.7 on 2026-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heropromotionimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='heropromotionimage',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heropromotionimage',
            name='sub_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
